# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6XcPtECWBguLpc1pwmuOJSRVA6SkZCE
"""

import streamlit as st
import numpy as np

st.title("Beam Path Optimizer")

# Generate random beam points
n = st.slider("Number of Beam Points", 10, 100, 30)

points = np.random.rand(n, 2) * 100

# Nearest-neighbor optimization
visited = [0]
unvisited = list(range(1, n))

while unvisited:
    last = visited[-1]

    next_point = min(
        unvisited,
        key=lambda i: np.linalg.norm(points[last] - points[i])
    )

    visited.append(next_point)
    unvisited.remove(next_point)

# Create optimized path coordinates
path_x = [points[i][0] for i in visited]
path_y = [points[i][1] for i in visited]

# Visualize with Streamlit native chart
st.line_chart(
    {
        "x": path_x,
        "y": path_y
    }
)

# Show optimized order
st.write("Optimized Beam Order:")
st.write(visited)
