# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6XcPtECWBguLpc1pwmuOJSRVA6SkZCE
"""

import streamlit as st
import numpy as np
import pandas as pd

# ============================================================
# PAGE SETUP
# ============================================================

st.set_page_config(page_title="Beam Path Optimization")

st.title("Electron Beam Path Optimization")
st.write("""
This application demonstrates how beam scan paths can be optimized
to reduce unnecessary movement in additive manufacturing.

The objective is simple:

→ Make the beam travel the shortest useful distance possible.
""")

# ============================================================
# USER INPUT
# ============================================================

st.header("1. Generate Beam Scan Points")

st.write("""
In real additive manufacturing systems, the beam must visit many
locations on a powder bed.

Each point represents a location where the beam must melt material.
""")

num_points = st.slider(
    "Number of Beam Exposure Points",
    10,
    100,
    30
)

# Generate random points
points = np.random.rand(num_points, 2) * 100

df = pd.DataFrame(points, columns=["X", "Y"])

st.write("Generated Beam Points")
st.dataframe(df)

# ============================================================
# ORIGINAL PATH
# ============================================================

st.header("2. Original Beam Path")

st.write("""
The simplest possible beam strategy is to scan the points
in the order they were generated.

This is inefficient because:

- the beam may jump across large distances,
- travel time increases,
- heat distribution becomes inconsistent,
- machine productivity decreases.

The original path below represents a non-optimized strategy.
""")

original_order = list(range(num_points))

original_x = [points[i][0] for i in original_order]
original_y = [points[i][1] for i in original_order]

original_chart = pd.DataFrame({
    "X": original_x,
    "Y": original_y
})

st.line_chart(original_chart)

# ============================================================
# DISTANCE FUNCTION
# ============================================================

st.header("3. Measuring Beam Travel Distance")

st.write("""
To optimize the beam movement, we first need to calculate
the distance between two beam positions.

Shorter distances mean:

- faster scanning,
- less idle movement,
- lower energy waste,
- smoother manufacturing behavior.
""")

def distance(p1, p2):
    return np.linalg.norm(p1 - p2)

# ============================================================
# PATH LENGTH FUNCTION
# ============================================================

st.header("4. Total Beam Travel")

st.write("""
The total beam travel distance is calculated by summing all
movement distances between consecutive points.

This value represents the amount of beam motion required
to complete the scan strategy.
""")

def total_distance(order, pts):

    total = 0

    for i in range(len(order) - 1):

        total += distance(
            pts[order[i]],
            pts[order[i + 1]]
        )

    return total

original_distance = total_distance(original_order, points)

st.metric(
    "Original Beam Travel Distance",
    f"{original_distance:.2f}"
)

# ============================================================
# OPTIMIZATION ALGORITHM
# ============================================================

st.header("5. Beam Path Optimization Algorithm")

st.write("""
This application uses a simple nearest-neighbor optimization strategy.

How it works:

1. Start at one beam point.
2. Find the closest unvisited point.
3. Move there.
4. Repeat until all points are visited.

Why this helps:

- reduces unnecessary travel,
- minimizes long jumps,
- improves scanning efficiency,
- creates smoother beam trajectories.

This is a simplified version of real industrial path-planning systems.
""")

visited = [0]
unvisited = list(range(1, num_points))

while unvisited:

    current = visited[-1]

    next_point = min(
        unvisited,
        key=lambda i: distance(points[current], points[i])
    )

    visited.append(next_point)

    unvisited.remove(next_point)

# ============================================================
# OPTIMIZED RESULTS
# ============================================================

st.header("6. Optimized Beam Path")

st.write("""
After optimization, the beam now follows a shorter and more
logical movement sequence.

This reduces:

- dead travel,
- unnecessary acceleration,
- thermal inconsistency,
- production time.
""")

optimized_x = [points[i][0] for i in visited]
optimized_y = [points[i][1] for i in visited]

optimized_chart = pd.DataFrame({
    "X": optimized_x,
    "Y": optimized_y
})

st.line_chart(optimized_chart)

# ============================================================
# PERFORMANCE COMPARISON
# ============================================================

st.header("7. Performance Comparison")

optimized_distance = total_distance(visited, points)

improvement = (
    (original_distance - optimized_distance)
    / original_distance
) * 100

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Original Distance",
        f"{original_distance:.2f}"
    )

with col2:
    st.metric(
        "Optimized Distance",
        f"{optimized_distance:.2f}"
    )

with col3:
    st.metric(
        "Improvement",
        f"{improvement:.2f}%"
    )

# ============================================================
# ENGINEERING INTERPRETATION
# ============================================================

st.header("8. Engineering Interpretation")

st.write(f"""
The optimized strategy reduced the total beam travel distance
by approximately {improvement:.2f}%.

In additive manufacturing systems, this can contribute to:

- faster print times,
- reduced energy usage,
- lower thermal stress,
- improved melt consistency,
- smoother machine operation.

This directly addresses the engineering problem:

'How can the beam travel the shortest useful distance?'
""")

# ============================================================
# RELATION TO OBP / OPENMELT
# ============================================================

st.header("9. Relation to OBP and OpenMelt")

st.write("""
This demonstration relates directly to OBP/OpenMelt concepts:

- Point generation,
- Beam trajectory planning,
- Path ordering,
- Timed movement,
- Scan optimization,
- Manufacturing efficiency.

In a real system:

Geometry
→ Scan Path Generation
→ Beam Ordering
→ OBP Commands
→ Machine Execution

The optimization step is critical because poor beam movement
can create:

- overheating,
- distortion,
- wasted motion,
- slower manufacturing.
""")

# ============================================================
# FINAL SUMMARY
# ============================================================

st.header("10. Final Summary")

st.success("""
This application successfully demonstrates a simplified
beam path optimization workflow for additive manufacturing.

Core achievement:
The beam now travels a shorter and more efficient path.
""")
