# -*- coding: utf-8 -*-
"""beam_path_optimizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jA-OEF9xWowWYz4phxyqwX8bFbaTy6wj
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from itertools import combinations

st.set_page_config(page_title="Beam Path Optimizer", layout="wide")

# -----------------------------
# Utility functions
# -----------------------------

def total_distance(points, order):
    dist = 0.0
    for i in range(len(order) - 1):
        p1 = points[order[i]]
        p2 = points[order[i + 1]]
        dist += np.linalg.norm(p1 - p2)
    return dist


def nearest_neighbor(points):
    n = len(points)
    visited = [False] * n
    order = [0]
    visited[0] = True

    for _ in range(n - 1):
        last = order[-1]
        dists = np.linalg.norm(points - points[last], axis=1)
        dists[visited] = np.inf
        next_idx = np.argmin(dists)
        order.append(next_idx)
        visited[next_idx] = True

    return order


def two_opt(points, order, max_iter=100):
    best = order.copy()
    best_dist = total_distance(points, best)

    for _ in range(max_iter):
        improved = False
        for i, j in combinations(range(1, len(order) - 1), 2):
            if j - i == 1:
                continue

            new_order = best[:]
            new_order[i:j] = reversed(best[i:j])

            new_dist = total_distance(points, new_order)

            if new_dist < best_dist:
                best = new_order
                best_dist = new_dist
                improved = True

        if not improved:
            break

    return best


def plot_paths(points, order_before, order_after):
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Before
    ax = axes[0]
    for i in range(len(order_before) - 1):
        p1 = points[order_before[i]]
        p2 = points[order_before[i + 1]]
        ax.plot([p1[0], p2[0]], [p1[1], p2[1]])
    ax.scatter(points[:, 0], points[:, 1])
    ax.set_title("Original Path")

    # After
    ax = axes[1]
    for i in range(len(order_after) - 1):
        p1 = points[order_after[i]]
        p2 = points[order_after[i + 1]]
        ax.plot([p1[0], p2[0]], [p1[1], p2[1]])
    ax.scatter(points[:, 0], points[:, 1])
    ax.set_title("Optimized Path")

    return fig


# -----------------------------
# UI
# -----------------------------

st.title("Beam Path Optimizer")
st.write("Optimize beam scan order to minimize travel distance.")

col1, col2 = st.columns(2)

with col1:
    num_points = st.slider("Number of beam points", 5, 200, 50)
    seed = st.number_input("Random seed", value=42)

with col2:
    use_2opt = st.checkbox("Enable 2-opt refinement", True)
    run_button = st.button("Run Optimization")

# -----------------------------
# Run logic
# -----------------------------

if run_button:
    np.random.seed(seed)

    # Generate random beam points
    points = np.random.rand(num_points, 2) * 100

    # Original order
    order_before = list(range(num_points))

    # Nearest neighbor
    order_nn = nearest_neighbor(points)

    # Optional 2-opt
    if use_2opt:
        order_after = two_opt(points, order_nn)
    else:
        order_after = order_nn

    # Distances
    dist_before = total_distance(points, order_before)
    dist_after = total_distance(points, order_after)

    improvement = (dist_before - dist_after) / dist_before * 100

    # Display metrics
    st.subheader("Results")
    col1, col2, col3 = st.columns(3)

    col1.metric("Original Distance", f"{dist_before:.2f}")
    col2.metric("Optimized Distance", f"{dist_after:.2f}")
    col3.metric("Improvement (%)", f"{improvement:.2f}%")

    # Plot
    fig = plot_paths(points, order_before, order_after)
    st.pyplot(fig)

    # Show order (optional debug)
    with st.expander("Show scan order"):
        st.write("Optimized order:", order_after)